import { createFileRoute } from "@tanstack/react-router";
import { PageShell, ArrowLink } from "@/components/site-shell";
import { FaqSection, MarketplaceBanner, PageIntro } from "@/components/page-sections";
import { completeSetNote, products } from "@/lib/site-content";
export const Route = createFileRoute("/produk")({ head: () => ({ meta: [
  { title: "Produk Pintu Willmore | Baja, Kayu, Aluminium, PVC & UPVC" }, { name: "description", content: "Jelajahi pilihan pintu baja, kayu, aluminium, PVC dan UPVC Willmore untuk kebutuhan rumah modern." },
  { property: "og:title", content: "Produk Pintu Willmore" }, { property: "og:description", content: "Pilihan material pintu untuk keamanan, karakter, dan fungsi ruang." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: ProductsPage });
function ProductsPage(){return <PageShell><PageIntro eyebrow="Koleksi Produk" title="Material yang tepat membentuk pengalaman ruang." text="Bandingkan karakter setiap material untuk menemukan pintu yang paling sesuai dengan fungsi, gaya, dan kebutuhan perawatan rumah Anda."/><section className="complete-set-note"><span>Lengkap &amp; Siap Pasang</span><p>{completeSetNote}</p></section><section className="catalog">{products.map((p)=><article key={p.slug} className="catalog-item"><div className="catalog-image"><img src={p.image} alt={p.name} loading="lazy" width={1200} height={1504}/><span>/{p.no}</span></div><div className="catalog-copy">{"badge" in p && <span className="tested-badge">{p.badge}</span>}<h2>{p.name}</h2><p>{p.summary}</p><ul>{p.points.map(point=><li key={point}>{point}</li>)}</ul></div></article>)}</section><MarketplaceBanner /><FaqSection number="01" /><section className="inline-cta"><h2>Belum yakin material mana yang tepat?</h2><ArrowLink to="/kontak">Konsultasikan kebutuhan Anda</ArrowLink></section></PageShell>}
