import { createFileRoute } from "@tanstack/react-router";
import { PageShell, ArrowLink } from "@/components/site-shell";
import { PageIntro, SectionHeading } from "@/components/page-sections";
import { heroImage } from "@/lib/site-content";

export const Route = createFileRoute("/tentang")({ head: () => ({ meta: [
  { title: "Tentang Willmore | Spesialis Pintu Sejak 2002" }, { name: "description", content: "Kenali Willmore, spesialis pintu yang mendampingi kebutuhan pelanggan dari konsultasi dan instalasi hingga after sales sejak 2002." },
  { property: "og:title", content: "Tentang Willmore | Spesialis Pintu Sejak 2002" }, { property: "og:description", content: "Pengalaman lebih dari dua dekade dalam membantu kebutuhan pintu." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: AboutPage });
function AboutPage(){return <PageShell><PageIntro eyebrow="Tentang Willmore" title="Dibangun dari pengalaman. Dijalankan dengan perhatian." text="Sejak 2002, Willmore hadir untuk membantu pelanggan menemukan pintu yang sesuai kebutuhan—bukan sekadar menjual produk."/><section className="wide-image"><img src={heroImage} alt="Pintu Willmore pada arsitektur kontemporer" width={1920} height={1088}/></section><section className="section-pad story-grid"><SectionHeading number="01" label="Cara Pandang" title="Kualitas dimulai dari memahami kebutuhan ruang."/><div className="story-copy"><p>Setiap rumah memiliki kebutuhan yang berbeda. Lokasi pintu, fungsi ruang, keamanan, ketahanan, perawatan, dan karakter desain perlu dipertimbangkan bersama.</p><p>Karena itu, Willmore menempatkan konsultasi sebagai awal dari proses. Pilihan material diterangkan dengan jernih, pemasangan menjadi bagian dari layanan, dan pendampingan berlanjut melalui after sales.</p><ArrowLink to="/kontak">Bicara dengan kami</ArrowLink></div></section><section className="principles"><div><span>01</span><h3>Relevan</h3><p>Produk dipilih sesuai kebutuhan nyata ruang.</p></div><div><span>02</span><h3>Menyeluruh</h3><p>Dari konsultasi hingga after sales.</p></div><div><span>03</span><h3>Berpengalaman</h3><p>Pengetahuan yang tumbuh sejak 2002.</p></div></section></PageShell>}
